export const APIURL: any = {
  GETPRODUCTS: `/products`,
  LOGIN: '/login',
  GET_ALL_PROPERTY: '/getAllListedProperty',
  SEE_DETAILS: '/getListedPropertyDetailsById',
  UNLIST_PROPERTY: '/unlistProperty',
  ADD_PROPERTY: '/addProperty',
  RESET_PASSWORD: '/resetPassword',
  PARTNER_REQUEST_LIST: '/partnerRequestsList',
  ACTION_PARTNER_REQUEST: '/createActionOnParterRequest',
  PARTNER_PROPERTY_REQUEST_LIST: '/propertyRequestsList',
  ACTION_PARTNER_PROPERTY: '/createActionOnPropertyRequest',
}

export const RESPONSES: any = {
  SUCCESS: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NOCONTENT: 204,
  BADREQUEST: 400,
  UN_AUTHORIZED: 401,
  INVALID_REQ: 422,
  FORBIDDEN: 403,
  NOTFOUND: 404,
  TIMEOUT: 408,
  TOOMANYREQ: 429,
  INTERNALSERVER: 500,
  BADGATEWAYS: 502,
  SERVICEUNAVILABLE: 503,
  GATEWAYTIMEOUT: 504,
}
